config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'show' => 'sessions#show'
  delete 'logout' => 'sessions#destroy'
  resources :hrdx_pegawais
  resources :attendance_sessions
  resources :attendance_logs, only: [:create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'sessions#new'

  # Defines the root path route ("/")
  # root "posts#index"
  resources :students, only: [:index]
end

app/models/attendance_session.rb
class AttendanceSession < ApplicationRecord
  validates :course, presence: true
  validates :name, presence: true, length: { minimum: 4, maximum: 100 }
  validates :begin, presence: true, format: { with: /\A([01]?[0-9]|2[0-3])\.[0-5][0-9]\z/,
                      message: "must be a valid time format (HH.mm)" }
  validates :room, presence: true, length: { minimum: 1, maximum: 20 }
  validates :summary, presence: true, length: { minimum: 4, maximum: 200 }
  # validates :course, presence: true
  belongs_to :hrdx_pegawai, foreign_key: 'pegawai_id'
  has_many :attendance_logs, dependent: :destroy

  def self.update_total_enrolled(total)
    self.update(:total_not_attend => total)
  end

  def self.update_secret_code
    self.update(:secret_code => generate_secret)
  end

  def self.generate_secret
    rand(1000..9999)
  end
end

app/controllers/attendance_sessions_controller.rb
class AttendanceSessionsController < ApplicationController
  before_action :redirect_to_login, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_attendance_session, only: [:show, :edit, :update, :destroy]
  before_action :set_pegawai, only: [:index, :new]
  before_action :set_attendance_dropdown, only: [:new, :edit, :index, :create, :update]

  def index
    #@attendance_sessions = current_hrdx_user.attendance_sessions.all
    @attendance_sessions = current_hrdx_user.attendance_sessions.order(created_at: :desc).limit(20)
    @attendance_session = current_hrdx_user.attendance_sessions.build
    #.limit(12)
    # @total_students = current_hrdx_user.total_students(@attendance_sessions)
  end

  def show
    @attendance_session = AttendanceSession.find(params[:id])
    @my_students = current_hrdx_user.my_students(@attendance_session.course)
    @not_attend = @attendance_session.attendance_logs
  end
  def new
    @attendance_session = current_hrdx_user.attendance_sessions.build
  end

  def create
    @attendance_session = current_hrdx_user.attendance_sessions.build(attendance_session_params)
    if @attendance_session.save
      @my_students = current_hrdx_user.my_students(@attendance_session.course)
      @attendance_session.update(total_not_attend: @my_students.count)
      @attendance_session.update(secret_code: AttendanceSession.generate_secret)
      # AttendanceSession.update_total_enrolled(@my_students.count)
      flash[:success] = "Attendance session has been created."
      redirect_to @attendance_session
    else
      render '_form'
    end
  end

  def edit
    @attendance_session = current_hrdx_user.attendance_sessions.find(params[:id])
  end

  def update
    @attendance_session = current_hrdx_user.attendance_sessions.find(params[:id])
    if @attendance_session.update(attendance_session_params)
      flash[:success] = "Attendance session has been updated."
      redirect_to @attendance_session
    else
      render :edit
    end
  end

  def destroy
    @attendance_session = current_hrdx_user.attendance_sessions.find(params[:id])
    @attendance_session.destroy!
    # @attendance_session.destroy!
    flash[:success] = "Attendance session has been deleted."
    redirect_to attendance_sessions_path
  end
  private
  def attendance_session_params
    params.require(:attendance_session).permit(
      :name, :begin, :summary, :room, :course)
  end

  def set_attendance_dropdown
    temp = current_hrdx_user.my_courses
    map_to_adak_pengajaran = AdakPengajaran.find(temp.pluck(:pengajaran_id))
    # @attendance_session_dropdown = KrkmKuliah.find(map_to_adak_pengajaran.pluck(:kuliah_id))
    @attendance_session_dropdown = map_to_adak_pengajaran.map do |pengajaran|
      {pengajaran_id: pengajaran.id, nama_kul_ind: KrkmKuliah.find(pengajaran.kuliah_id).nama_kul_ind}
    end
    @attendance_session_dropdown.sort_by! { |h| h[:nama_kul_ind] }
  end

  def set_attendance_session
    @attendance_session = AttendanceSession.find_by(id: params[:id])
    if @attendance_session == nil
      return redirect_to root_path
    end
    redirect_to root_path unless @attendance_session.hrdx_pegawai == current_hrdx_user
  end
end

app/helpers/attendance_sessions_helper.rb
module AttendanceSessionsHelper
  def list_not_attended(student_dim)
    DimxDim.find_by(dim_id: student_dim)
  end
end

app/views/attendance_sessions/_form.html.erb
<% provide(:title, "Attendance Session") %>
<% if @attendance_session.errors.any? %>
  <div class="alert alert-danger">
    <strong><%= pluralize(@attendance_session.errors.count, "error") %> prohibited this attendance session:</strong>
    <ul>
      <% @attendance_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @attendance_session, scope: :attendance_session, local: true, data: {turbo: false}) do |f|%>
  <div class="mb-3">
    <%= f.label :choose_your_course, class: "form-label" %>
    <div class="input-group">
      <span class="input-group-text"><i class="bi bi-book-fill"></i></span>
      <%= f.select :course, options_for_select(
        @attendance_session_dropdown.map{ |option| [option[:nama_kul_ind],
                                                    option[:pengajaran_id]] }), {}, {class: 'form-select',
                                                                                     required: true} %>
    </div>
  </div>
  <div class="mb-3">
    <%= f.label :session_name, class: "form-label" %>
    <div class="input-group">
      <span class="input-group-text"><i class="bi bi-card-text"></i></span>
      <%= f.text_field :name, id: "session_name",class: "form-control",placeholder: 'Enter session name',required: true %>
    </div>
  </div>
  <div class="mb-3">
    <%= f.label :summary, class: "form-label" do %>
      Summary
      <span class="bi bi-info-circle-fill" data-bs-toggle="tooltip" title="Please enter a brief summary of the session"></span>
    <% end %>
    <div class="input-group">
      <span class="input-group-text"><i class="bi bi-list-check"></i></span>
      <%= f.text_area :summary, id: "summary", class: "form-control", placeholder: 'Enter summary', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
      <%= f.label :time_begin, class: "form-label" do %>
        Time begin
        <span class="bi bi-info-circle-fill" data-bs-toggle="tooltip" title="Enter the start time in the format HH.MM"></span>
      <% end %>
      <div class="input-group">
          <span class="input-group-text"><i class="bi bi-clock-fill"></i></span>
          <%= f.text_field :begin, value: Time.now.strftime('%H.%M'),class: "form-control",
                           placeholder: 'Enter start time 08.15',required: true %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :room_name, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-text"><i class="bi bi-house-door-fill"></i></span>
          <%= f.select :room, options_for_select(MrefRLokasi.available_locations), {},
                       {class: 'form-select', required: true} %>
        </div>
      </div>
    </div>
  </div>
  <%= f.button type: 'submit', class: "btn btn-primary" do %>
    <i class="bi bi-plus-circle-fill"></i> Create session
  <% end %>
<% end %>

<script>
  document.getElementById('session_name').addEventListener('input', function() {
    document.getElementById('summary').value = this.value;
  });
</script>

app/views/attendance_sessions/edit.html.erb
<div class="modal fade show d-block" id="editSessionModal" tabindex="-1" aria-labelledby="editSessionModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title" id="editSessionModalLabel"><i class="bi bi-calendar-check-fill"></i> Edit Attendance Session</h5>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<script>
    var myModal = new bootstrap.Modal(document.getElementById('editSessionModal'), {
        backdrop: 'static',
        keyboard: false
    })
    myModal.show()

    $('#editSessionModal').on('hidden.bs.modal', function (e) {
        window.location.href = "<%= attendance_sessions_path %>";
    })
</script>

app/views/attendance_sessions/index.html.erb
<div class="d-flex align-items-center my-4">
<!--  <i class="bi bi-calendar-check-fill me-2"></i>-->
  <h1 class="mb-0">Manage Attendance Sessions</h1>
</div>
<hr/>
<div class="fixed-bottom m-3 p-2 text-end">
  <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#newSessionModal">
    <i class="bi bi-plus-circle-fill"></i> New Session
  </button>
</div>

<div class="modal fade" id="newSessionModal" tabindex="-1" aria-labelledby="newSessionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title" id="newSessionModalLabel"><i class="bi bi-calendar-check-fill"></i> New Attendance Session</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', attendance_session: @attendance_session %>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-4 g-4"> <!-- 4 cards per row -->
  <% @attendance_sessions.each_with_index do |attendance_session, index| %>
    <div class="col">
      <%= link_to attendance_session, class: 'text-decoration-none text-dark' do %>
      <div class="card h-100 shadow-lg rounded hover-shadow">
        <div class="card-header text-white"
             style="background: linear-gradient(to right,
               <%= %w[#ff5f6d #ffc371 #24C6DC #514A9D #FF512F #DD2476 #DA22FF #9733EE][index % 8] %>,
               <%= %w[#ffc371 #24C6DC #514A9D #FF512F #DD2476 #DA22FF #9733EE #ff5f6d][(index+1) % 8] %>);">
          <i class="bi bi-calendar-check-fill"></i> <%= attendance_session.name.split[0..3].join(' ') %>
        </div>
        <div class="card-body">
          <p class="card-text"><i class="bi bi-card-text"></i> <%= attendance_session.summary.split[0..9].join(' ') %></p>

          <ul class="list-group list-group-flush">
            <li class="list-group-item"><i class="bi bi-person-check-fill"></i>
              Total Absences : <%= attendance_session.attendance_logs.count %></li>
            <li class="list-group-item"><i class="bi bi-person-x-fill"></i>
              Total Attendees : <%= attendance_session.total_not_attend-attendance_session.attendance_logs.count%></li>
            <li class="list-group-item"><i class="bi bi-book-fill"></i> Room Name :
              <%= MrefRLokasi.get_location_name(attendance_session.room ) %></li>
          </ul>
        </div>
        <%end %>
        <div class="card-footer">
          <%= link_to '<i class="bi bi-pencil-fill"></i> Edit'.html_safe,
                      edit_attendance_session_path(attendance_session), class: 'btn btn-primary' %>
          <%= link_to '<i class="bi bi-eye-fill"></i> View'.html_safe,
                      attendance_session, class: 'btn btn-success' %>
          <%= link_to '<i class="bi bi-trash-fill"></i> Remove'.html_safe,
                      attendance_session, data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete?'},
                      class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/attendance_sessions/new.html.erb
<% provide(:title, "Attendance Session") %>
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-header bg-primary text-white">
          <h1 class="h3 mb-0"><i class="bi bi-calendar-check-fill"></i> Attendance Session</h1>
        </div>
        <div class="card-body">
          <%= form_with(model: @attendance_session,
                        scope: :attendance_session, local: true, data: {turbo: false}) do |f|%>
            <div class="mb-3">
              <%= f.label :Pilih_mata_kuliah, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-book-fill"></i></span>
                <%= f.select :course, options_for_select(
                  @attendance_session_dropdown.map{ |option| [option[:nama_kul_ind],
                                                              option[:pengajaran_id]] }), {}, {class: 'form-select',
                                                                                               required: true} %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :nama_sesi, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-card-text"></i></span>
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :mulai, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-clock-fill"></i></span>
                <%= f.text_field :begin, class: "form-control" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :berakhir, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-clock-fill"></i></span>
                <%= f.text_field :end, class: "form-control" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :summary, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-list-check"></i></span>
                <%= f.text_field :summary, class: "form-control" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :ruangan, class: "form-label" %>
              <div class="input-group">
                <span class="input-group-text"><i class="bi bi-house-door-fill"></i></span>
                <%= f.text_field :room, class: "form-control" %>
              </div>
            </div>
            <%= f.submit "Buat sesi", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendance_sessions/show.html.erb
<div id="show-view">

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card shadow-lg rounded">
        <div class="card-header text-left bg-primary text-white">
          <h4 class="mb-0" style="font-family: 'Arial', sans-serif; font-weight: 300;">
            <i class="bi bi-journal-text me-2"></i> <i>Topic: <%= @attendance_session.name %></i>
          </h4>
        </div>
        <div class="card-body">
<!--          <p><strong>Topic :</strong> <%#= @attendance_session.name %></p>-->
<!--          <p><strong>Summary :</strong> <%#= @attendance_session.summary %></p>-->
<!--          <p><strong>Total Enrolled Students :</strong> <%#= @my_students.count %></p>-->
          <%= form_with(url: attendance_logs_path, method: :post, local: true, data: {turbo: false}) do %>
            <%=hidden_field_tag :attendance_session_id, @attendance_session.id %>
            <% if flash[:alert] %>
              <div class="alert alert-danger">
                <i class="bi bi-info-circle-fill"></i> <%= flash[:alert] %>
              </div>
            <% end %>
            <div class="alert alert-info" role="alert">
              <i class="bi bi-info-circle-fill"></i> Please enter the provided token before closing the session.
            </div>
            <div class="input-group mb-3">
              <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
              <%= text_field_tag :secret_code, nil, required: true,placeholder: 'Enter token ( provided by student )',
                                 class: 'form-control', title: 'Token is provided by the student' %>
            </div>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="enrolled-tab"
                        data-bs-toggle="tab" data-bs-target="#enrolled" type="button"
                        role="tab" aria-controls="enrolled" aria-selected="true">Enrolled
                  <span class="badge bg-success small-badge"><%= @my_students.count %></span>
                </button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="not-attend-tab" data-bs-toggle="tab"
                        data-bs-target="#not-attend" type="button" role="tab"
                        aria-controls="not-attend" aria-selected="false">Not Attend
                  <span class="badge bg-danger small-badge"><%= @not_attend.count %></span>
                </button>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="enrolled" role="tabpanel" aria-labelledby="enrolled-tab">
                <table class="table table-striped table-hover">
                  <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
<!--                    <th scope="col">NIM</th>-->
                    <th scope="col">Status</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @my_students.each_with_index do |student, index| %>
                    <tr>
                      <th scope="row"><%= index + 1 %></th>
                      <td><%= student.nama.split[0..1].join(' ') %></td>
<!--                      <td><%#= student.nim %></td>-->
                      <td>
                        <select name="attendance_logs[<%= student.id %>][status]" class="form-select">
                          <%= options_for_select(AttendanceStatus.available_status) %>
                        </select>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
                <button type="submit" class="btn btn-success position-fixed bottom-0 end-0 m-3">
                  <i class="bi bi-alarm-fill"></i> Close Session
                </button>
              </div>
              <div class="tab-pane fade" id="not-attend" role="tabpanel" aria-labelledby="not-attend-tab">
                <table class="table table-striped table-hover">
                  <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">NIM</th>
                    <th scope="col">Status</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @not_attend.each_with_index do |student, index| %>
                    <tr>
                      <th scope="row"><%= index + 1 %></th>
                      <td><%= list_not_attended(student.dim).nama.split[0..1].join(' ') %></td>
                      <td><%= list_not_attended(student.dim).nim %></td>
                      <td>
                      <%= AttendanceStatus.find(student.status).status %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>