config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'show' => 'sessions#show'
  delete 'logout' => 'sessions#destroy'
  resources :hrdx_pegawais
  resources :attendance_sessions
  resources :attendance_logs, only: [:create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'sessions#new'

  # Defines the root path route ("/")
  # root "posts#index"
  resources :students, only: [:index]
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-white" style="background-color: #0a4275;">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: CTA -->
    <section class="">
      <p class="d-flex justify-content-center align-items-center">
        <span class="me-3">Feel free to fork this project and improve the app</span>
        <a href="https://github.com/MichaelSipayung/DelAttendanceApp" target="_blank" class="btn btn-outline-light btn-rounded">
          <i class="bi bi-github" role="img" aria-label="GitHub"></i> GitHub
        </a>
      </p>
    </section>
    <!-- Section: CTA -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    ©<%= Time.now.year %> Copyright:
    <a class="text-white" href="https://www.del.ac.id/">Del Institute of Technology</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-lg">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand d-flex align-items-center' do %>
      <i class="bi bi-calendar-check" style="font-size: 1.5rem;"></i>
      <span class="ms-2">Attendance App</span>
    <% end %>
<!--    <a class="navbar-brand d-flex align-items-center" href="#">-->
<!--      <i class="bi bi-calendar-check" style="font-size: 1.5rem;"></i>-->
<!--      <span class="ms-2">Attendance App</span>-->
<!--    </a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarContent" aria-controls="navbarContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active d-flex align-items-center" aria-current="page" href="#">-->
<!--            <i class="bi bi-house-door-fill" style="font-size: 2rem;"></i>-->
<!--            <span class="ms-2">Home</span>-->
<!--          </a>-->
<!--        </li>-->
        <li class="nav-item">
          <% if !logged_in? %>
            <%= link_to login_path, class: 'nav-link d-flex align-items-center' do %>
              <i class="bi bi-box-arrow-in-right" style="font-size: 2rem;"></i>
              <span class="ms-2">Login</span>
            <% end %>
          <% else %>
            <%= link_to logout_path, data: {turbo_method: "delete",
                                                     turbo_confirm: "Logout from account?"},
                        class: 'nav-link d-flex align-items-center' do %>
              <i class="bi bi-box-arrow-right" style="font-size: 2rem;"></i>
              <span class="ms-2">Logout</span>
            <% end %>
          <% end %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center"
               href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-list-check" style="font-size: 2rem;"></i>
              <span class="ms-2">Attendance</span>
            </a>
            <ul class="dropdown-menu">
<!--              <li><a class="dropdown-item d-flex align-items-center" href="#">-->
<!--                <i class="bi bi-card-list" style="font-size: 2rem;"></i>-->
<!--                <span class="ms-2">All Attendances</span>-->
<!--              </a></li>-->
              <% if log_in_as_student? %>
                <%= link_to students_path, class: "dropdown-item d-flex align-items-center" do%>
                  <i class="bi bi-card-list" style="font-size: 2rem;"></i>
                  <span class="ms-2">Secret Code (Token)</span>
                <% end %>
                <%else %>
                  <%= link_to attendance_sessions_path, class: "dropdown-item d-flex align-items-center" do%>
                    <i class="bi bi-card-list" style="font-size: 2rem;"></i>
                    <span class="ms-2">Manage Attendance</span>
                  <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>